wandb_version: 1

SWA:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
batch_size:
  desc: null
  value: 16
dataset:
  desc: null
  value: v1
epochs:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.005
momentum:
  desc: null
  value: 0.8
no_cuda:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
seed:
  desc: null
  value: 42
test_batch_size:
  desc: null
  value: 16
